                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               :
    name: "Choose a punishment type:"
    size: 9
    items:
        1:
            name: "&2 Player Info"
            material: SKULL_ITEM
            slot: 0
            playerinfo: true
            lore:
              -  "&6 %playername%"
              -  "&6 %uuid%"
              -  "&c Click to see past infractions"
              -  "&c from this player!"
        2:
            name: "&4 Kick-Warn"
            material: REDSTONE
            slot: 3
            lore:
              -  "&c Click to kick or warn"
              -  "&c a player!"
        3:
            name: "&4 Mute"
            material: SULPHUR
            slot: 5
            lore:
              -  "&c Click to mute a player!"
        4:
            name: "&4 Ban"
            material: GLOWSTONE_DUST
            ban: true
            slot: 7
            lore:
              -  "&c Click to ban a player!"

2:
    name: ""
    size:
    items:
        1:
            name: ""
            material:
            slot:
            lore:
              -
        2:
            name: ""
            material:
            slot:
            lore:
              -
        3:
            name: ""
            material:
            slot:
            lore:
              -
        4:
            name: ""
            material:
            slot:
            lore:
              -